### ISSUE TITLE
Add a logo/link to home page in top bar

### ISSUE THREAD

**Issue by Yuripetusko** [rmrk-team/rmrk-composable-nft-creator#7]
**Is your feature request related to a problem? Please describe.**
There should be an easy way to go to home page at any time

**Describe the solution you'd like**
Title

**Describe alternatives you've considered**
Title

**Additional context**
Title

**Comment by shubhankar-shandilya-india** [comment]
Hi @Yuripetusko Could you please tell me what exactly you are looking for? 
should I make a navbar with logo which will redirect to homepage when clicked or you just need an logo at top right 
and where is the logo to be used ?

**Comment by Yuripetusko** [comment]
> Hi @Yuripetusko Could you please tell me what exactly you are looking for? should I make a navbar with logo which will redirect to homepage when clicked or you just need an logo at top right and where is the logo to be used ?

There's no logo for this project, so it's fine to generate one with AI, based on the name of the repo or something like this, and add it to <TopBar component. Clicking on Logo should always lead to home page `/` route, using nextjs Link

**Comment by shubhankar-shandilya-india** [comment]
Also could you please tell do you a need a navbar with full width or just a logo at top left like your connect wallet button ?

**Comment by Yuripetusko** [comment]
> Also could you please tell do you a need a navbar with full width or just a logo at top left like your connect wallet button ?


There is already <Topbar component, currently there's a wallet connect button in there. So we can just place logo in the same component but align it to the left

**Comment by shubhankar-shandilya-india** [comment]
ok sure i will work on it

**Comment by shubhankar-shandilya-india** [comment]
if possible could you please provide the logo as you know better what kind of logo you are looking for  @Yuripetusko

**Comment by Yuripetusko** [comment]
> if possible could you please provide the logo as you know better what kind of logo you are looking for @Yuripetusko

Here you go: https://drive.google.com/file/d/1x4bmIGHP4LO3T9VfCboZkT5YssSHrZFC/view?usp=sharing

**Comment by shubhankar-shandilya-india** [comment]
Thank you I am working on it you can assign this issue to me .

**Comment by shubhankar-shandilya-india** [comment]
Hi @Yuripetusko i am facing this error while setting this project locally
npm error code ENOENT
npm error syscall lstat
npm error errno -4058
npm error enoent ENOENT: no such file or directory, lstat
npm error enoent This is related to npm not being able to find a file.

Could you please help me with setting it locally

**Comment by shubhankar-shandilya-india** [comment]
Hi @Yuripetusko  just wanted to know that can I just use Image tag and useRouter from NextJS and give the size prop to logo and one inline style like cursor pointer 
Is that fine or do I need to do any other way?
